// sellerActionTypes.js
export const SELLER_REGISTER_REQUEST = "SELLER_REGISTER_REQUEST";
export const SELLER_REGISTER_SUCCESS = "SELLER_REGISTER_SUCCESS";
export const SELLER_REGISTER_FAILURE = "SELLER_REGISTER_FAILURE";

export const SELLER_LOGIN_REQUEST = "SELLER_LOGIN_REQUEST";
export const SELLER_LOGIN_SUCCESS = "SELLER_LOGIN_SUCCESS";
export const SELLER_LOGIN_FAILURE = "SELLER_LOGIN_FAILURE";

export const GET_SELLER_REQUEST = "GET_SELLER_REQUEST";
export const GET_SELLER_SUCCESS = "GET_SELLER_SUCCESS";
export const GET_SELLER_FAILURE = "GET_SELLER_FAILURE";
