export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST";
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS";
export const GET_ORDER_BY_ID_FAILURE = "GET_ORDER_BY_ID_FAILURE";

/* export const GET_ORDER_HISTORY_REQUEST = 'GET_ORDER_HISTORY_REQUEST';
export const GET_ORDER_HISTORY_SUCCESS = 'GET_ORDER_HISTORY_SUCCESS';
export const GET_ORDER_HISTORY_FAILURE = 'GET_ORDER_HISTORY_FAILURE'; 
 */

export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAILURE = "GET_ALL_ORDERS_FAILURE";

export const GET_ORDERS_BY_USERID_REQUEST = "GET_ORDERS_BY_USERID_REQUEST";
export const GET_ORDERS_BY_USERID_SUCCESS = "GET_ORDERS_BY_USERID_SUCCESS";
export const GET_ORDERS_BY_USERID_FAILURE = "GET_ORDERS_BY_USERID_FAILURE";

export const GET_ORDERS_BY_SELLERID_REQUEST = "GET_ORDERS_BY_SELLERID_REQUEST";
export const GET_ORDERS_BY_SELLERID_SUCCESS = "GET_ORDERS_BY_SELLERID_SUCCESS";
export const GET_ORDERS_BY_SELLERID_FAILURE = "GET_ORDERS_BY_SELLERID_FAILURE";
