// actionTypes.js

export const FETCH_COLORS_REQUEST = "FETCH_COLORS_REQUEST";
export const FETCH_COLORS_SUCCESS = "FETCH_COLORS_SUCCESS";
export const FETCH_COLORS_FAILURE = "FETCH_COLORS_FAILURE";

export const FETCH_SIZES_REQUEST = "FETCH_SIZES_REQUEST";
export const FETCH_SIZES_SUCCESS = "FETCH_SIZES_SUCCESS";
export const FETCH_SIZES_FAILURE = "FETCH_SIZES_FAILURE";
