export const FETCH_SELLER_PRODUCTS_REQUEST = "FETCH_SELLER_PRODUCTS_REQUEST";
export const FETCH_SELLER_PRODUCTS_SUCCESS = "FETCH_SELLER_PRODUCTS_SUCCESS";
export const FETCH_SELLER_PRODUCTS_FAILURE = "FETCH_SELLER_PRODUCTS_FAILURE";
